version: "3.7"

networks:
  language_gpt_network:
    name: ${DOCKER_NETWORK_NAME}
    driver: bridge

volumes:
  mongo_data_db: { }

services:
  project:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - language_gpt_network
    depends_on:
      - mongodb
    env_file:
      - .env
      - .env-docker
    command: ['poetry', 'run', 'project-dev']

  mongodb:
    image: mongo:6.0.5
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=project
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:${DOCKER_MONGO_CONTAINER_PORT}:27017"
    volumes:
      - mongo_data_db:/data/db
    command: mongod --wiredTigerCacheSizeGB 2 --port 27017
    networks:
      - language_gpt_network
